version: '3'

services:
  idalighting:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    # Thêm các biến môi trường khác nếu cần 